version: '3.7'

services:
  web:
    build: 
      context: ./app
      dockerfile: Dockerfile.prod
    # command: gunicorn chatapp.wsgi:application --bind 0.0.0.0:8000
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    image:
      - 066234982609.dkr.ecr.us-east-1.amazonaws.com/we-chat:latest
    depends_on:
      - db

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 80:80
    depends_on:
      - web
  
  redis:
    image: "redis:alpine"
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  postgres_data:
  static_volume: