version: '3.7'

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - ./.env

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=chat
      - POSTGRES_PASSWORD=chat
      - POSTGRES_DB=chat_dev
  
  redis:
    image: "redis:alpine"
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  postgres_data: