# Generated by Django 3.1.1 on 2020-09-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='room',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
