# Generated by Django 3.1.1 on 2020-09-08 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200908_1517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='created_at',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='user',
            new_name='nickname',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='text',
        ),
    ]
