# Generated by Django 3.0.7 on 2020-11-10 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20200908_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='censored',
            field=models.BooleanField(default=False),
        ),
    ]
